import { AppDefinition } from "@/types/os";

export const APP_DEFINITIONS: AppDefinition[] = [
  {
    id: "terminal",
    title: "Terminal",
    icon: "terminal",
    description: "A lightweight terminal styled for the Choco Pie desktop.",
    desktop: false,
    singleInstance: false,
    defaultSize: { width: 640, height: 400 },
    minSize: { width: 360, height: 220 },
  },
  {
    id: "files",
    title: "File Manager",
    icon: "files",
    description: "Browse files with a PCManFM-inspired layout.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 760, height: 500 },
    minSize: { width: 520, height: 320 },
  },
  {
    id: "browser",
    title: "Chromium",
    icon: "browser",
    description: "A browser shell with a Choco Pie OS start page.",
    desktop: false,
    singleInstance: false,
    defaultSize: { width: 920, height: 580 },
    minSize: { width: 540, height: 360 },
  },
  {
    id: "settings",
    title: "Control Centre",
    icon: "settings",
    description: "Appearance, device, and desktop preferences.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 680, height: 500 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: "vscode",
    title: "VSCode Lite",
    icon: "vscode",
    description: "A lightweight coding workspace for simple C, C++, Java, HTML, and Python practice.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 1160, height: 760 },
    minSize: { width: 820, height: 560 },
  },
  {
    id: "text-editor",
    title: "Text Editor",
    icon: "text-editor",
    description: "A simple text editor for quick notes and code snippets.",
    desktop: false,
    singleInstance: false,
    defaultSize: { width: 720, height: 520 },
    minSize: { width: 460, height: 320 },
  },
  {
    id: "document-viewer",
    title: "Document Viewer",
    icon: "document-viewer",
    description: "Read a few bundled documents in a lightweight viewer.",
    desktop: false,
    singleInstance: false,
    defaultSize: { width: 760, height: 560 },
    minSize: { width: 520, height: 360 },
  },
  {
    id: "media-player",
    title: "Media Player",
    icon: "media-player",
    description: "Play sample audio and video items with simple controls.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 700, height: 500 },
    minSize: { width: 460, height: 320 },
  },
  {
    id: "image-viewer",
    title: "Image Viewer",
    icon: "image-viewer",
    description: "Preview wallpapers and sample gallery images.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 760, height: 540 },
    minSize: { width: 520, height: 360 },
  },
  {
    id: "gamepi",
    title: "GamePi",
    icon: "game-center",
    description: "A simple game storefront for launching pi-themed desktop games.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 1180, height: 780 },
    minSize: { width: 840, height: 620 },
  },
  {
    id: "memory-tile",
    title: "Memory Tile",
    icon: "game-center",
    description: "Memorize and replay pi-inspired number patterns.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 1100, height: 760 },
    minSize: { width: 820, height: 580 },
  },
  {
    id: "neon-rush",
    title: "NeonRush",
    icon: "game-center",
    description: "A fast neon arcade runner with reflex-heavy action.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 1100, height: 760 },
    minSize: { width: 820, height: 580 },
  },
  {
    id: "pi-piano-tiles",
    title: "Pi Piano Tiles",
    icon: "game-center",
    description: "Tap rhythm tiles and keep pace with pi-powered musical sequences.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 1100, height: 760 },
    minSize: { width: 820, height: 580 },
  },
  {
    id: "pie-ninja",
    title: "Pie Ninja",
    icon: "game-center",
    description: "Slice through flying pies in a quick arcade challenge.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 1100, height: 760 },
    minSize: { width: 820, height: 580 },
  },
  {
    id: "riddles",
    title: "Riddles",
    icon: "game-center",
    description: "Solve themed riddles and logic prompts around pi and puzzles.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 1000, height: 720 },
    minSize: { width: 760, height: 560 },
  },
  {
    id: "whispering-shadows",
    title: "The Whispering Shadows",
    icon: "game-center",
    description: "A moody story-driven mystery game set inside a haunted mansion.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 1180, height: 780 },
    minSize: { width: 860, height: 620 },
  },
  {
    id: "pi-snake",
    title: "Pi Snake",
    icon: "pi-snake",
    description: "A lightweight Snake game where you eat the digits of pi in the correct order.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 980, height: 760 },
    minSize: { width: 760, height: 580 },
  },
  {
    id: "slice-the-pie",
    title: "Slice the Pie",
    icon: "slice-the-pie",
    description: "A pie-slicing puzzle game with equal shares, irrational ratios, and pi-angle goals.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 980, height: 720 },
    minSize: { width: 720, height: 540 },
  },
  {
    id: "pi-defender",
    title: "Pi Defender",
    icon: "pi-defender",
    description: "A circular tower defense arcade where the digits of pi shape every enemy wave.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 1180, height: 780 },
    minSize: { width: 820, height: 620 },
  },
  {
    id: "calculator",
    title: "Calculator",
    icon: "calculator",
    description: "Basic arithmetic calculator.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 340, height: 460 },
    minSize: { width: 300, height: 420 },
  },
  {
    id: "archiver",
    title: "Archiver",
    icon: "files",
    description: "Browse archive contents and simulate extraction.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 620, height: 460 },
    minSize: { width: 420, height: 320 },
  },
  {
    id: "menu-editor",
    title: "Main Menu Editor",
    icon: "settings",
    description: "Toggle sample menu entries on and off.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 640, height: 470 },
    minSize: { width: 460, height: 340 },
  },
  {
    id: "diagnostics",
    title: "Choco Pie Diagnostics",
    icon: "settings",
    description: "Run lightweight desktop health checks.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 660, height: 500 },
    minSize: { width: 460, height: 340 },
  },
  {
    id: "imager",
    title: "Choco Pie Imager",
    icon: "choco",
    description: "Choose an OS image and simulate writing to storage.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 720, height: 520 },
    minSize: { width: 480, height: 360 },
  },
  {
    id: "sd-card-copier",
    title: "SD Card Copier",
    icon: "document-viewer",
    description: "Simulate copying one SD card image to another device.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 660, height: 460 },
    minSize: { width: 460, height: 320 },
  },
  {
    id: "task-manager",
    title: "Task Manager",
    icon: "task-manager",
    description: "Inspect open desktop windows and close them.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 720, height: 500 },
    minSize: { width: 480, height: 340 },
  },
  {
    id: "about",
    title: "About \u03c0",
    icon: "pi",
    description: "A dedicated desktop page for mathematical pi.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 980, height: 720 },
    minSize: { width: 620, height: 460 },
  },
  {
    id: "piday",
    title: "Pi Day",
    icon: "piday",
    description: "Explore Pi Day traditions, history, and celebrations.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 900, height: 680 },
    minSize: { width: 620, height: 460 },
  },
  {
    id: "raspberrypi",
    title: "Raspberry Pi",
    icon: "raspberry",
    description: "A visual guide to Raspberry Pi boards, milestones, and impact.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 940, height: 700 },
    minSize: { width: 640, height: 460 },
  },
  {
    id: "piart",
    title: "Pi Art",
    icon: "piart",
    description: "Generate colorful artworks driven by the digits of pi.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 920, height: 700 },
    minSize: { width: 620, height: 460 },
  },
  {
    id: "symphony",
    title: "Pi Symphony",
    icon: "symphony",
    description: "Turn pi into an audiovisual composition with motion and rhythm.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 960, height: 700 },
    minSize: { width: 640, height: 460 },
  },
  {
    id: "explorer",
    title: "Pi Explorer",
    icon: "explorer",
    description: "Search, inspect, and jump through the digits of pi.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 900, height: 660 },
    minSize: { width: 620, height: 420 },
  },
  {
    id: "simulation",
    title: "Pi Simulation",
    icon: "simulation",
    description: "Interactive simulations showing how pi appears in geometry and probability.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 960, height: 700 },
    minSize: { width: 640, height: 460 },
  },
  {
    id: "games",
    title: "Pi Games",
    icon: "game-center",
    description: "Play small pi-themed games inside the desktop.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 920, height: 700 },
    minSize: { width: 620, height: 460 },
  },
  {
    id: "quiz",
    title: "Pi Quiz",
    icon: "quiz",
    description: "Test your pi knowledge with a large randomized quiz bank.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 960, height: 720 },
    minSize: { width: 640, height: 460 },
  },
  {
    id: "mandala",
    title: "Pi Mandala",
    icon: "mandala",
    description: "An infinite zoom mandala powered by drifting pi digits.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 1100, height: 760 },
    minSize: { width: 720, height: 520 },
  },
  {
    id: "gallery",
    title: "Pi Gallery",
    icon: "gallery",
    description: "Browse a local gallery of pi, Raspberry Pi, and mathematics imagery.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 1120, height: 760 },
    minSize: { width: 720, height: 520 },
  },
  {
    id: "pico-playground",
    title: "Pico Playground",
    icon: "pico",
    description: "Launch Pico Playground exactly as provided.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 1180, height: 780 },
    minSize: { width: 860, height: 620 },
  },
  {
    id: "raspberry-pi-5-simulator",
    title: "Raspberry Pi 5 Simulator",
    icon: "raspberry-pi5",
    description: "Launch Raspberry Pi 5 Simulator exactly as provided.",
    desktop: true,
    singleInstance: true,
    defaultSize: { width: 1180, height: 780 },
    minSize: { width: 860, height: 620 },
  },
  {
    id: "run-dialog",
    title: "Run",
    icon: "terminal",
    description: "Quickly launch apps by typing a command.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 480, height: 240 },
    minSize: { width: 400, height: 220 },
  },
  {
    id: "shutdown-dialog",
    title: "Shutdown",
    icon: "settings",
    description: "Desktop power actions and session controls.",
    desktop: false,
    singleInstance: true,
    defaultSize: { width: 480, height: 300 },
    minSize: { width: 420, height: 260 },
  },
];

export const APP_MAP = Object.fromEntries(
  APP_DEFINITIONS.map((app) => [app.id, app]),
) as Record<AppDefinition["id"], AppDefinition>;
